version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    groups:
      all-actions:
        patterns: [ "*" ]

  - package-ecosystem: "gradle"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "org.springframework.boot*"
      all-other-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "org.springframework*"
          - "org.springframework.boot*"
