server.servlet.context-path: /ia-tjenester-metrikker
server.port: 9090

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: prometheus
      base-path: /internal/actuator

spring:
  config.activate.on-profile: compose

  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      username: postgres
      password: test
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 2
      minimum-idle: 1
      initialization-fail-timeout: 60000
  flyway:
    locations: classpath:/db/migration, classpath:/db/test-lokaldb-data

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: http://localhost:6969/tokenx/.well-known/openid-configuration
      accepted_audience: aud-localhost

tokenx-service:
  client-id: localhost:arbeidsgiver:ia-tjenester-metrikker
  token_endpoint: http://localhost:6969/tokenx/.well-known/openid-configuration/token
  altinn_rettigheter_proxy_audience: localhost:arbeidsgiver:altinn-rettigheter-proxy
  private_jwk: '{
      "kty": "RSA",
      "d": "BRcX3ywynvH9WA5wOz_vU9HzSY6OkmRKOGGqLEG_fEtVcXwxReSSuVcXZUngZrPkoC3li-jvNfDz9c_7WP44HkO07RkG10mSspLjS-EarYg5HUI8JPfrjtacCVmq0pnVlvEeR-35x1e91o6iC5-hEGQPkBgImKwuFy1u2eiPBM-mIoNHOSpO5IqHBAP2Gi2w7SU28mZ1xt2xmvj6kGE96u3G6nSkr175tgdi0tHO9T7BCYFjr1NNkLojzExpo5gUVyNsm17ahMi2XE7NIRdduHkEXcprr5DayDK7_VaQYqa3OPsN3UcRZanXcpdFt9HHt8KyuRW3zvXJ6-AtM1UCkQ",
      "e": "AQAB",
      "use": "sig",
      "kid": "1",
      "n": "ssXDjDMHXWxvnAFXwJiKqgyf6tn_zHGbkSiWNgHZ2xsQgxo-gzv5JssbJxLCDZCdC5zX7nXIHOC5fid_fxMXGNAYh6xaJzxSLGGAJHSp_uCh5zSPAGFigihxLNwwWaDxYDcLFC9QHzaV__BaB_JUaHyD7aFDUEyQiB4MXAqTkCEUmPj-RTiUbcnicD5Q32zByJ8gzG3ufxuCGnP-xcc5QJQ8TmrlLgNzgiHHdkpRjeXCHovP_gYGXujJkhQ0dvgYtVpgoHeGcH1FC9ZRd6IiFtanJ1MPwg2i6sR_HlE2l3Ua_Knj4FZY3F0cM3P4AgXI8TyEhQgM2GWwPGf6YNrHyQ"
  }'

altinn-proxy:
  proxyUrl: http://localhost:${wiremock.port}/proxy/
  fallbackUrl: http://localhost:${wiremock.port}/altinn/
  altinnApiKey: "local-altinn-API-key"
  apiGwKey: "local-API-GW-key"

enhetsregisteret:
  url: "http://localhost:8585/enhetsregisteret/"

wiremock:
  port: 8585
