server.servlet.context-path: /ia-tjenester-metrikker

# Expose the prometheus endpoint /internal/actuator/prometheus, disable all other endpoints
management:
  endpoint.prometheus.enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: prometheus
      base-path: /internal/actuator

spring:
  config.activate.on-profile: prod-gcp
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 2
      minimum-idle: 1
      initialization-fail-timeout: 60000
  flyway:
    locations: classpath:/db/migration, classpath:/db/privileges

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

no.nav.security.jwt.issuer:
  tokenx:
    discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
    accepted_audience: ${TOKEN_X_CLIENT_ID}

tokenx-service:
  client-id: ${TOKEN_X_CLIENT_ID}
  token_endpoint: ${TOKEN_X_TOKEN_ENDPOINT}
  private_jwk: ${TOKEN_X_PRIVATE_JWK}
  altinn_rettigheter_proxy_audience: prod-gcp:arbeidsgiver:altinn-rettigheter-proxy

altinn-proxy:
  proxyUrl: http://altinn-rettigheter-proxy.arbeidsgiver/altinn-rettigheter-proxy
  fallbackUrl: https://api-gw.oera.no/
  altinnApiKey: ${ALTINN_APIKEY}
  apiGwKey: ${ALTINN_APIGW_APIKEY}

enhetsregisteret:
  url: "https://data.brreg.no/enhetsregisteret/api/"

