spring:
  config.activate.on-profile: dev-gcp
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      maximum-pool-size: 2
  flyway:
    locations: classpath:/db/migration, classpath:/db/privileges
