server.servlet.context-path: /ia-tjenester-metrikker

spring:
  config.activate.on-profile: labs-gcp

  datasource:
    hikari:
      jdbc-url: "jdbc:h2:mem:local-db"
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximum-pool-size: 2
      minimum-idle: 1
      initialization-fail-timeout: 60000

  h2.console:
    enabled: true
    path: /h2

  flyway:
    locations: classpath:/db/migration

no.nav.security.jwt.issuer:
  selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    cookiename: selvbetjening-idtoken

altinn:
  proxyUrl: http://localhost:${wiremock.port}/proxy/
  fallbackUrl: http://localhost:${wiremock.port}/altinn/
  altinnApiKey: "labs-altinn-API-key"
  apiGwKey: "labs-API-GW-key"

wiremock:
  port: 8585