server.servlet.context-path: /ia-tjenester-metrikker

spring:
  config.activate.on-profile: prod-gcp
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 2
      minimum-idle: 1
      initialization-fail-timeout: 60000
  flyway:
    locations: classpath:/db/migration, classpath:/db/privileges

no.nav.security.jwt.issuer:
  selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    cookiename: selvbetjening-idtoken
