spring:
  config.activate.on-profile: local
  h2.console:
    enabled: true
    path: /h2

  datasource:
    url: "jdbc:h2:mem:${DATABASE_DATABASE}"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    locations: classpath:/db/migration
