spring:
  profiles:
    active: local

  h2.console:
    enabled: true
    path: /h2

  datasource:
    hikari:
      jdbc-url: "jdbc:h2:mem:${DATABASE_DATABASE}"
      username: sa
      password:
      maximum-pool-size: 2
      driver-class-name: org.h2.Driver

  flyway:
    locations: classpath:/db/migration

