INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999999999',
        86901,
        'DIGITAL_IA_TJENESTE',
        'SYKEFRAVÆRSSTATISTIKK',
        9,
        'Hjemmesykepleie',
        'Helsetjenester',
        6500,
        'Kommuneforvaltningen',
        'IKKE_TILGJENGELIG',
        '1532',
        'GISKE');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999999999',
        86901,
        'DIGITAL_IA_TJENESTE',
        'SAMTALESTØTTE',
        9,
        'Hjemmesykepleie',
        'Helsetjenester',
        6500,
        'Kommuneforvaltningen',
        'IKKE_TILGJENGELIG',
        '1532',
        'GISKE');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999999999',
        86901,
        'DIGITAL_IA_TJENESTE',
        'SAMTALESTØTTE',
        9,
        'Hjemmesykepleie',
        'Helsetjenester',
        6500,
        'Kommuneforvaltningen',
        'IKKE_TILGJENGELIG',
        '1532',
        'GISKE');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999999888',
        62020,
        'DIGITAL_IA_TJENESTE',
        'SYKEFRAVÆRSSTATISTIKK',
        9,
        'Konsulentvirksomhet tilknyttet informasjonsteknologi',
        'Tjenester tilknyttet informasjonsteknologi',
        2100,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '1149',
        'KARMØY');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('988888888',
        88911,
        'DIGITAL_IA_TJENESTE',
        'SYKEFRAVÆRSSTATISTIKK',
        19,
        'Barnehager',
        'Helse- og sosialtjenester',
        2100,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '1149',
        'KARMØY');
INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('988888888',
        88911,
        'DIGITAL_IA_TJENESTE',
        'SYKEFRAVÆRSSTATISTIKK',
        19,
        'Barnehager',
        'Helse- og sosialtjenester',
        2100,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '1149',
        'KARMØY');
INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('977777777',
        42130,
        'DIGITAL_IA_TJENESTE',
        'SYKEFRAVÆRSSTATISTIKK',
        120,
        'Bygging av bruer og tunneler',
        'Bygge- og anleggsvirksomhet',
        2100,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '0301',
        'OSLO');
INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('966666666',
        10520,
        'DIGITAL_IA_TJENESTE',
        'SAMTALESTØTTE',
        8,
        'Produksjon av iskrem',
        'Produksjon av nærings- og nytelsesmidler',
        2100,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '5401',
        'TROMSØ');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('955555555',
        87102,
        'DIGITAL_IA_TJENESTE',
        'SAMTALESTØTTE',
        99,
        'Somatiske sykehjem',
        'Helse- og sosialtjenester',
        2100,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '1828',
        'NESNA');


INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('955545556',
        87102,
        'DIGITAL_IA_TJENESTE',
        'SAMTALESTØTTE',
        99,
        'Somatiske sykehjem',
        'Helse- og sosialtjenester',
        2100,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '1828',
        'NESNA');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999997888',
        62020,
        'DIGITAL_IA_TJENESTE',
        'SYKEFRAVÆRSSTATISTIKK',
        9,
        'Konsulentvirksomhet tilknyttet informasjonsteknologi',
        'Tjenester tilknyttet informasjonsteknologi',
        2100,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '1149',
        'KARMØY');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999997888',
        62023,
        'DIGITAL_IA_TJENESTE',
        'SYKEFRAVÆRSSTATISTIKK',
        9,
        'Konsulentvirksomhet tilknyttet informasjonsteknologi',
        'Tjenester tilknyttet informasjonsteknologi',
        2110,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '0574',
        'OSLO');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999997888',
        62023,
        'DIGITAL_IA_TJENESTE',
        'SYKEFRAVÆRSSTATISTIKK',
        9,
        'Konsulentvirksomhet tilknyttet informasjonsteknologi',
        'Tjenester tilknyttet informasjonsteknologi',
        2110,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '0574',
        'OSLO');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999997888',
        62023,
        'DIGITAL_IA_TJENESTE',
        'NETTKURS',
        9,
        'Konsulentvirksomhet tilknyttet informasjonsteknologi',
        'Tjenester tilknyttet informasjonsteknologi',
        2110,
        'Private aksjeselskaper mv.',
        'IKKE_TILGJENGELIG',
        '0574',
        'OSLO');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999997888',
        62023,
        'DIGITAL_IA_TJENESTE',
        'FOREBYGGE_FRAVÆR',
        9,
        'Hjemmesykepleie',
        'Helsetjenester',
        6500,
        'Kommuneforvaltningen',
        'IKKE_TILGJENGELIG',
        '4623',
        'KRISTIANSAND');

INSERT INTO metrikker_ia_tjenester_innlogget(orgnr,
                                             naering_kode_5siffer,
                                             form_av_tjeneste,
                                             kilde_applikasjon,
                                             antall_ansatte,
                                             naering_kode5siffer_beskrivelse,
                                             naering_2siffer_beskrivelse,
                                             ssb_sektor_kode,
                                             ssb_sektor_kode_beskrivelse,
                                             fylke,
                                             kommunenummer,
                                             kommune)
VALUES ('999997888',
        62023,
        'DIGITAL_IA_TJENESTE',
        'KALKULATOR',
        9,
        'Hjemmesykepleie',
        'Helsetjenester',
        6500,
        'Kommuneforvaltningen',
        'IKKE_TILGJENGELIG',
        '4623',
        'KRISTIANSAND');