apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: ia-tjenester-metrikker-alert
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: '#arbeidsgiver-teamia-alerts-dev'
      prependText: '<!channel> | '
  alerts:
    - alert: applikasjon nede
      expr: sum(up{app="ia-tjenester-metrikker", job="kubernetes-pods"}) == 0
      for: 2m
      description: "ia-tjenester-metrikker er nede"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.nais.io/d/VniEA46Mz/ia-tjenester-metrikker"

    - alert: det har skjedd en feil i ia-tjenester-metrikker
      expr: sum(increase(logd_messages_total{log_app="ia-tjenester-metrikker",log_level="Error"}[10m])) > 0
      for: 10s
      description: "ia-tjenester-metrikker har logget en feil"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.nais.io/d/VniEA46Mz/ia-tjenester-metrikker"

    - alert: Få ia-tjenester-metrikker (uinnlogget)
      expr: rate(counted_uinnlogget_mottatt_iatjeneste_total{app="ia-tjenester-metrikker"}[10m]) == 0
      for: 2m
      description: "Ingen ia-tjenester-metrikk (uinnlogget) lagret ila de siste 10 minutter"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.nais.io/d/VniEA46Mz/ia-tjenester-metrikker"

    - alert: Få ia-tjenester-metrikker (innlogget)
      expr: rate(counted_innlogget_mottatt_iatjeneste_total{app="ia-tjenester-metrikker"}[2d]) == 0
      for: 2m
      description: "Ingen ia-tjenester-metrikk lagret (innnlogget) ila de siste 48 timer"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.nais.io/d/VniEA46Mz/ia-tjenester-metrikker"
