apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ia-tjenester-metrikker-alert
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  groups:
    - name: ia-tjenester-metrikker-alerts
      rules:
        - alert: Ingen metrikk registrert for applikasjon
          expr: vector(1)
          for: 20s
          annotations:
            consequence: "Vi mottar ikke metrikker for tjeneste {{ $labels.kilde }}"
            description: "Har ikke registrert noen IA-metrikker til {{ $labels.kilde }} de siste 24 timer"
            action: |-
              Verifiser at metrikkene fungerer som de skal. TEST!
            labels:
              namespace: teamia
              severity: critical
