apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: ia-tjenester-metrikker-alert
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: '#arbeidsgiver-teamia-alerts-dev'
      prependText: '<!channel> | '
  alerts:
    - alert: applikasjon nede
      expr: sum(up{app="ia-tjenester-metrikker", job="kubernetes-pods"}) == 0
      for: 2m
      description: "ia-tjenester-metrikker er nede"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.nais.io/d/VniEA46Mz/ia-tjenester-metrikker"

    - alert: det har skjedd en feil i ia-tjenester-metrikker
      expr: sum(increase(logd_messages_total{log_app="ia-tjenester-metrikker",log_level="Error"}[10m])) > 0
      for: 10s
      description: "ia-tjenester-metrikker har logget en feil"
      action: "Sjekk logs.adeo.no for logger, og Grafana-dashboardet vårt: https://grafana.nais.io/d/VniEA46Mz/ia-tjenester-metrikker"

    - alert: Få ia-tjenester-metrikker (uinnlogget)
      expr: sum(increase(counted_uinnlogget_mottatt_iatjeneste_total{app="ia-tjenester-metrikker"}[12h])) == 0
      for: 2m
      description: "Ingen ia-tjenester-metrikk (uinnlogget) lagret ila de siste 12 timer"
      action: "Sjekk logs her: https://logs.adeo.no/app/discover#/view/cd953fb0-f262-11ec-a21b-2f67f808c51c?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-2d%2Cto%3Anow)), og Grafana-dashboardet vårt: https://grafana.nais.io/d/VniEA46Mz/ia-tjenester-metrikker"

    - alert: Få ia-tjenester-metrikker (innlogget)
      expr: sum(increase(counted_innlogget_mottatt_iatjeneste_total{app="ia-tjenester-metrikker"}[48h])) == 0
      for: 2m
      description: "Ingen ia-tjenester-metrikk lagret (innnlogget) ila de siste 48 timer"
      action: "Sjekk logs her: https://logs.adeo.no/app/discover#/view/48722640-f262-11ec-a21b-2f67f808c51c?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-2d%2Cto%3Anow)), og Grafana-dashboardet vårt: https://grafana.nais.io/d/VniEA46Mz/ia-tjenester-metrikker"
