apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ia-tjenester-metrikker-alert
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  groups:
    - name: ia-tjenester-metrikker-alerts
      rules:
        - alert: ApplikasjonNede
          expr: sum(up{app="ia-tjenester-metrikker"}) == 0
          for: 2m
          annotations:
            consequence: "ia-tjenester-metrikker er utilgjengelig"
            action: |-
              Sjekk helsa til applikasjonen ved å kjøre
              `kubectl describe pod <podname> -n arbeidsgiver` og 
              `kubectl logs <podname> -n arbeidsgiver`
          labels:
            namespace: teamia
            severity: critical
        - alert: ErrorLogRegistrert
          expr: sum(increase(logd_messages_total{log_app="ia-tjenester-metrikker",log_level="Error"}[10m])) > 0
          annotations:
            description: "ia-tjenester-metrikker har logget en (eller flere) feil."
            action: |-
              Sjekk logs.adeo.no for logger, 
              eller Grafana-dashboardet vårt: https://grafana.nais.io/dashboards/f/cvOhCMUnz/team-ia
          labels:
            namespace: teamia
            severity: warning
        - alert: IngenMetrikkRegistrert
          expr: sum by(kilde) (increase(innloggede_ia_tjenester_metrikker_persistert_total[48h])) == 0
          group_by: [ kilde ]
          annotations:
            description: "Har ikke registrert noen IA-metrikker til {{ $labels.kilde }} de siste 48 timer"
            action: |-
              Verifiser at metrikkene fungerer som de skal. 
              Dette kan være en normal situasjon dersom vi har lite trykk på tjenestene våre.
          labels:
            namespace: teamia
            severity: warning
