apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ia-tjenester-metrikker
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://ia-tjenester-metrikker.intern.dev.nav.no/ia-tjenester-metrikker
  liveness:
    path: /ia-tjenester-metrikker/internal/isalive
    initialDelay: 60
  readiness:
    path: /ia-tjenester-metrikker/internal/isready
    initialDelay: 60
  prometheus:
    enabled: true
    path: /ia-tjenester-metrikker/internal/actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: loki
        - id: elastic
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-f1-micro
        databases:
          - name: ia-tjenester-metrikker
            envVarPrefix: DATABASE
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: ARBEIDSGIVER_ALTINN_TILGANGER_URL
      value: http://arbeidsgiver-altinn-tilganger.fager
    - name: ARBEIDSGIVER_ALTINN_TILGANGER_AUDIENCE
      value: dev-gcp:fager:arbeidsgiver-altinn-tilganger
  envFrom:
    - secret: ia-tjenester-metrikker-secrets
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: min-ia
          namespace: pia
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
      external:
        - host: data.brreg.no