apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ia-tjenester-metrikker
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /internal/isalive
    initialDelay: 60
  readiness:
    path: /internal/isready
    initialDelay: 60
  kafka:
    pool: {{kafka_pool}}
  prometheus:
    enabled: true
    path: /ia-tjenester-metrikker/internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: ia-tjenester-metrikker
            envVarPrefix: DATABASE
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring_profile_active}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: ia-tjenester-metrikker-secrets
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: sykefravarsstatistikk
          namespace: arbeidsgiver
          cluster: dev-gcp
        - application: samtalestotte-arbeidsgiver
          namespace: arbeidsgiver
          cluster: dev-gcp
        - application: min-ia
          namespace: teamia
          cluster: dev-gcp
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
