apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ia-tjenester-metrikker
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  port: 8222
  ingresses:
  {{#each ingress as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /internal/isalive
  readiness:
    path: /internal/isready
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: ia-tjenester-metrikker
            envVarPrefix: DATABASE
