apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ia-tjenester-metrikker-topic
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: {{ kafka_pool }} # hard-code to nav-dev when running kubectl apply
  acl:
    - team: arbeidsgiver
      application: ia-tjenester-metrikker
      access: readwrite   # read, write, readwrite
