name: Deploy alerts to dev-gcp
on:
  push:
    paths:
      - 'nais/alerts.yaml'
      - 'github/workflows/deploy-alerts-dev.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/alerts.yaml