name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
      - prometheus
    paths:
      - 'nais/alerts-dev.yaml'
      - 'nais/alerts-prod.yaml'
      - 'github/deploy-alerts.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to clusters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/alerts-dev.yaml
      - name: deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/alerts-prod.yaml