name: Build and deploy
run-name: Build and deploy ~~ "${{ github.event.head_commit.message }}"
on:
  push:
    branches:
      - main
      - dependency-update-apr-2024
    paths-ignore:
      - '**.md'
      - '**/**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-push:
    name: Build, test and push docker image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Build project with Gradle
        run: ./gradlew clean build
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamia
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy-to-dev:
    permissions:
      id-token: write
    name: Deploy to dev-gcp
    needs: docker-build-push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ needs.docker-build-push.outputs.image }}
          RESOURCE: nais/dev.yaml

  deploy-to-prod:
    permissions:
      id-token: write
    if: github.ref == 'refs/heads/main'
    name: Deploy to prod-gcp
    needs: docker-build-push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          IMAGE: ${{ needs.docker-build-push.outputs.image }}
          RESOURCE: nais/prod.yaml

  trivy-scan:
    name: Scanner docker image med Trivy
    if: github.ref == 'refs/heads/main'
    needs: docker-build-push
    permissions:
      contents: read # to write sarif
      security-events: write # push sarif to github security
      id-token: write # for nais/login
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/pia-actions/trivy-scan@v1 # https://github.com/navikt/pia-actions/tree/main/trivy-scan
        with:
          image: ${{ needs.docker-build-push.outputs.image }}
          team: teamia
          upload-artifact: true
